/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ippon.datalake;

import com.google.common.io.Resources;
import org.junit.Test;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Simple Proof of Concept test against sample data,
 * ensuring my pre-processing script performs the steps it should.
 */
public class CSVIngestTest {
    
    @Test
    public void testHandleCSVIngest() throws IOException, URISyntaxException {
        List<String> massagedOutput = null;
        massagedOutput = CSVIngest.handleCSVIngest(
                new BufferedReader(
                        new FileReader(
                                new File(Resources.getResource("testData.csv").toURI()))));
        String output = massagedOutput.stream().map(x -> x + "\n").collect(Collectors.joining());
        System.out.println(output);
    }
}
